import oracledb
import os
from dotenv import load_dotenv

load_dotenv()

def init_db():
    print("🔌 Initializing Database Schema...")
    try:
        # Connect as Admin to create App User
        conn = oracledb.connect(
            user=os.getenv("DB_ADMIN_USER"),
            password=os.getenv("DB_ADMIN_PASSWORD"),
            dsn=os.getenv("DB_DSN")
        )
        cursor = conn.cursor()
        
        # Create User
        app_user = os.getenv("DB_APP_USER")
        app_pass = os.getenv("DB_APP_PASSWORD")
        try:
            cursor.execute(f"CREATE USER {app_user} IDENTIFIED BY {app_pass} QUOTA UNLIMITED ON USERS")
            cursor.execute(f"GRANT CONNECT, RESOURCE TO {app_user}")
        except:
            print("   -> User exists, skipping creation.")
        
        conn.close()

        # Connect as App User to create Table
        conn = oracledb.connect(user=app_user, password=app_pass, dsn=os.getenv("DB_DSN"))
        cursor = conn.cursor()
        
        try:
            cursor.execute("DROP TABLE talent_roster PURGE")
        except: pass

        cursor.execute("""
            CREATE TABLE talent_roster (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                actor_name VARCHAR2(100),
                min_fee_usd NUMBER,
                availability_status VARCHAR2(20),
                internal_rating NUMBER
            )
        """)
        
        data = [
            ('Cillian Murphy', 7000000, 'AVAILABLE', 9),
            ('Pedro Pascal', 6000000, 'AVAILABLE', 10),
            ('Florence Pugh', 4500000, 'BOOKED', 10)
        ]
        
        cursor.executemany("INSERT INTO talent_roster (actor_name, min_fee_usd, availability_status, internal_rating) VALUES (:1, :2, :3, :4)", data)
        conn.commit()
        print("✅ Database Ready!")
    except Exception as e:
        print(f"❌ Error: {e}")

if __name__ == "__main__":
    init_db()