import oracledb
import os
from dotenv import load_dotenv
from langchain_ollama import OllamaEmbeddings

load_dotenv()

def init_db():
    print("🔌 Initializing Database Schema...")
    
    # Initialize Embedding Model
    print("   -> Loading Embedding Model (nomic-embed-text)...")
    embeddings = OllamaEmbeddings(model="nomic-embed-text")

    try:
        # Connect as Admin to create App User
        conn = oracledb.connect(
            user=os.getenv("DB_ADMIN_USER"),
            password=os.getenv("DB_ADMIN_PASSWORD"),
            dsn=os.getenv("DB_DSN")
        )
        cursor = conn.cursor()
        
        # Create User
        app_user = os.getenv("DB_APP_USER")
        app_pass = os.getenv("DB_APP_PASSWORD")
        try:
            cursor.execute(f"CREATE USER {app_user} IDENTIFIED BY {app_pass} QUOTA UNLIMITED ON USERS")
            cursor.execute(f"GRANT CONNECT, RESOURCE, DB_DEVELOPER_ROLE TO {app_user}")
        except:
            print("   -> User exists, skipping creation.")
        
        conn.close()

        # Connect as App User to create Table
        conn = oracledb.connect(user=app_user, password=app_pass, dsn=os.getenv("DB_DSN"))
        cursor = conn.cursor()
        
        try:
            cursor.execute("DROP TABLE talent_roster PURGE")
        except: pass

        # Create Table with VECTOR type
        # Note: VECTOR column stores embeddings. Default for nomic-embed-text is 768 dims.
        cursor.execute("""
            CREATE TABLE talent_roster (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                actor_name VARCHAR2(100),
                min_fee_usd NUMBER,
                availability_status VARCHAR2(20),
                internal_rating NUMBER,
                bio VARCHAR2(4000),
                param_vector VECTOR
            )
        """)
        
        raw_data = [
            ('Cillian Murphy', 7000000, 'AVAILABLE', 9, 
             'Intense, distinctive Irish actor known for complex roles in Peaky Blinders and Oppenheimer. Great for psychological thrillers and leadership roles.'),
            
            ('Pedro Pascal', 6000000, 'AVAILABLE', 10,
             'Charismatic, rugged actor known for The Mandalorian and The Last of Us. Excellent for action, sci-fi, and protective father figures.'),
            
            ('Florence Pugh', 4500000, 'BOOKED', 10,
             'Versatile, emotional powerhouse known for Midsommar and Black Widow. Great for period dramas and intense emotional thrillers.')
        ]

        print("   -> Generating Vector Embeddings for Seed Data...")
        final_data = []
        import array
        for row in raw_data:
            # Embed the Bio
            vector = embeddings.embed_query(row[4]) 
            # Convert list to array.array for oracledb VECTOR support
            vector_array = array.array('d', vector)
            # Append vector to row tuple -> (name, fee, status, rating, bio, vector)
            final_data.append(row + (vector_array,))
        
        cursor.executemany("""
            INSERT INTO talent_roster 
            (actor_name, min_fee_usd, availability_status, internal_rating, bio, param_vector) 
            VALUES (:1, :2, :3, :4, :5, :6)
        """, final_data)
        
        conn.commit()
        print("✅ Database Ready with Vectors!")
    except Exception as e:
        print(f"❌ Error: {e}")

if __name__ == "__main__":
    init_db()