import oracledb
import os
from dotenv import load_dotenv
from langchain_ollama import OllamaEmbeddings

load_dotenv()

def init_db():
    print("🔌 Initializing Database Schema...")
    
    # Initialize Embedding Model
    print("   -> Loading Embedding Model (nomic-embed-text)...")
    embeddings = OllamaEmbeddings(model="nomic-embed-text")

    try:
        # Connect as Admin to create App User
        conn = oracledb.connect(
            user=os.getenv("DB_ADMIN_USER"),
            password=os.getenv("DB_ADMIN_PASSWORD"),
            dsn=os.getenv("DB_DSN")
        )
        cursor = conn.cursor()
        
        # Create User
        app_user = os.getenv("DB_APP_USER")
        app_pass = os.getenv("DB_APP_PASSWORD")
        try:
            cursor.execute(f"CREATE USER {app_user} IDENTIFIED BY {app_pass} QUOTA UNLIMITED ON USERS")
            cursor.execute(f"GRANT CONNECT, RESOURCE, DB_DEVELOPER_ROLE TO {app_user}")
        except:
            print("   -> User exists, skipping creation.")
        
        conn.close()

        # Connect as App User to create Table
        conn = oracledb.connect(user=app_user, password=app_pass, dsn=os.getenv("DB_DSN"))
        cursor = conn.cursor()
        
        try:
            cursor.execute("DROP TABLE talent_roster PURGE")
        except: pass

        # Create Table with VECTOR type
        # Note: VECTOR column stores embeddings. Default for nomic-embed-text is 768 dims.
        cursor.execute("""
            CREATE TABLE talent_roster (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                actor_name VARCHAR2(100),
                min_fee_usd NUMBER,
                availability_status VARCHAR2(20),
                internal_rating NUMBER,
                bio VARCHAR2(4000),
                param_vector VECTOR
            )
        """)
        
        raw_data = [
            ('Cillian Murphy', 7000000, 'AVAILABLE', 9, 
             'Intense, distinctive Irish actor known for complex roles in Peaky Blinders and Oppenheimer. Great for psychological thrillers and leadership roles.'),
            ('Pedro Pascal', 6000000, 'AVAILABLE', 10,
             'Charismatic, rugged actor known for The Mandalorian and The Last of Us. Excellent for action, sci-fi, and protective father figures.'),
            ('Florence Pugh', 4500000, 'BOOKED', 10,
             'Versatile, emotional powerhouse known for Midsommar and Black Widow. Great for period dramas and intense emotional thrillers.'),
            ('Keanu Reeves', 12000000, 'AVAILABLE', 10,
             'Legendary action star known for John Wick and The Matrix. specializes in stoic heroes, high-octane action, and sci-fi.'),
            ('Tom Hardy', 8500000, 'AVAILABLE', 9,
             'Physically creating and gritty actor known for Mad Max and Venom. Perfect for dark, brooding, or physically demanding roles.'),
            ('Idris Elba', 8000000, 'AVAILABLE', 10,
             'Commanding British actor known for Luther and The Wire. Brings gravitas, authority, and intense charisma to thrillers and dramas.'),
            ('Anya Taylor-Joy', 5000000, 'AVAILABLE', 9,
             'Unique, ethereal presence known for The Queen\'s Gambit and The Witch. Excellent for psychological horror, period pieces, and high-fashion drama.'),
            ('Timothée Chalamet', 6000000, 'BOOKED', 9,
             'Young, brooding heartthrob known for Dune and Call Me by Your Name. specialized in coming-of-age drama and sci-fi epics.'),
            ('Viola Davis', 7500000, 'AVAILABLE', 10,
             'Powerhouse dramatic actress known for Fences and The Woman King. Brings incredible emotional depth, strength, and authority.'),
            ('Daniel Kaluuya', 6500000, 'AVAILABLE', 9,
             'Intense and captivating actor known for Get Out and Judas and the Black Messiah. Master of psychological tension and social commentary.'),
            ('Margot Robbie', 11000000, 'AVAILABLE', 10,
             'Dynamic, high-energy star known for Barbie and Wolf of Wall Street. Brilliant at comedy, chaotic characters, and producing.'),
            ('Emma Stone', 9000000, 'AVAILABLE', 10,
             'Witty, expressive Oscar winner known for La La Land and Poor Things. Great for dark comedy, musicals, and quirky, complex leads.'),
            ('Ryan Gosling', 10000000, 'AVAILABLE', 9,
             'Charismatic leading man known for Drive and Barbie. Can do brooding silent types or hilarious comedic beat perfection.'),
            ('Zendaya', 8000000, 'BOOKED', 9,
             'Gen Z icon known for Euphoria and Dune. Brings raw emotion, style, and a modern edge to dramatic and sci-fi roles.'),
            ('Willem Dafoe', 3000000, 'AVAILABLE', 10,
             'Distinctive character actor known for The Lighthouse and Spider-Man. Perfect for villains, unhinged characters, and artistic horror.'),
            ('Jenna Ortega', 4000000, 'AVAILABLE', 8,
             'Rising star known for Wednesday and Scream. The new face of horror and dark comedy with a deadpan delivery.')
        ]

        print("   -> Generating Vector Embeddings for Seed Data...")
        final_data = []
        import array
        for row in raw_data:
            vector = embeddings.embed_query(row[4]) 
            vector_array = array.array('d', vector)
            final_data.append(row + (vector_array,))
        
        cursor.executemany("""
            INSERT INTO talent_roster 
            (actor_name, min_fee_usd, availability_status, internal_rating, bio, param_vector) 
            VALUES (:1, :2, :3, :4, :5, :6)
        """, final_data)
        
        conn.commit()
        print("✅ Database Ready with Vectors!")
    except Exception as e:
        print(f"❌ Error: {e}")

if __name__ == "__main__":
    init_db()